### ISSUE TITLE
[Bug]: keepFoldsAcrossSessions causes filetypes to be incorrect when switching back from oil.nvim

### ISSUE THREAD

**Issue by wSedlacek** [chrisgrieser/nvim-origami#1]
### Bug Description

The filetype gets stuck as `oil` when switching to and from `oil.nvim`
I have observed this behavior on both `rust` and `typescript` files (Using `rust-tools` and `typescript-tools`)
It doesn't appear on every file (maybe it is related to the folds present in that file?)

### Relevant Screenshot

https://github.com/chrisgrieser/nvim-origami/assets/8206108/bed6f482-0fa0-490d-ac63-1a6d4ecec1c5

### neovim version

```Text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
that is weird, I cannot really think of why that would happen. 

[the code for remembering folds is fairly straightforward](https://github.com/chrisgrieser/nvim-origami/blob/main/lua/origami.lua#L45-L69) and only ~20 lines. if anyone wants to take a look?

Also, I am not really familiar with oil.nvim. Is `oil` a filetype that also has folds? And if so, are they folds where it makes sense for nvim-origami to remember them? Because simply adding `oil` to the list of ignored filetypes would be fairly simple.

**Comment by wSedlacek** [comment]
I have quite a few plugins so it could be a combination of interactions [1]. Can't say for sure but the binary search uncovered that disabling this option caused the issue to not occur. I am happy with the option disabled for now, but thought I would share in case anyone else is trying to hunt down this weird behavior.

[1] - I haven't done an isolation of just oil.nvim and nvim-origami

**Comment by chrisgrieser** [comment]
This is likely fixed with 6d5e72f. Let me know if not, and I'll re-open
